(defun saludarcase (nombre)
    (case nombre 
          ((juan) '(Hola juan))
          ((maria) '(Hola maria))
          ((lupe) '(Hola lupe))
          (otherwise '(no se quien seas))
    )
)

(defun saludar (nombre)
    (cond ((eq nombre 'juan) '(Hola juan))
          ((eq nombre 'maria) '(Hola maria))
          ((eq nombre 'lupe) '(Hola lupe))
          (t '(no se quien seas))
    )
)

(defun saluda(nombre)
    (unless (string= nombre "")
        (format t "Hola, a!%" nombre)
        )
)